name = "uditmathur-github"
compatibility_date = "2026-06-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"
main = "./_worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"
